openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.1
paths:
  /api/users/del:
    delete:
      summary: "ere"
      description: "fddfd"
      responses:
        200:
          description: "delete"
