version: '3'

services:
  postgres:
    image: postgres:14
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_schema.sql
    container_name: spring-app-postgres-14
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=siteDB'
  spring-app:
    build: ./
    container_name: 'spring-app'
    ports:
      - "80:80"